// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package federationmanagementv1

import (
	context "context"
	types "github.com/spiffe/spire-api-sdk/proto/spire/api/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// FederationManagementClient is the client API for FederationManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FederationManagementClient interface {
	// Lists federation relationships with other trust domains.
	//
	// The caller must be local or present an admin X509-SVID.
	ListFederationRelationships(ctx context.Context, in *ListFederationRelationshipsRequest, opts ...grpc.CallOption) (*ListFederationRelationshipsResponse, error)
	// Gets a federation relationship with other trust domain.
	// If there is no federation relationship with the specified
	// trust domain, NOT_FOUND is returned.
	//
	// The caller must be local or present an admin X509-SVID.
	GetFederationRelationship(ctx context.Context, in *GetFederationRelationshipRequest, opts ...grpc.CallOption) (*types.FederationRelationship, error)
	// Batch creates one or more federation relationships with other trust domains.
	//
	// The caller must be local or present an admin X509-SVID.
	BatchCreateFederationRelationship(ctx context.Context, in *BatchCreateFederationRelationshipRequest, opts ...grpc.CallOption) (*BatchCreateFederationRelationshipResponse, error)
	// Batch updates one or more federation relationships with other trust domains.
	//
	// The caller must be local or present an admin X509-SVID.
	BatchUpdateFederationRelationship(ctx context.Context, in *BatchUpdateFederationRelationshipRequest, opts ...grpc.CallOption) (*BatchUpdateFederationRelationshipResponse, error)
	// Batch deletes federation relationships with other trust domains.
	//
	// The caller must be local or present an admin X509-SVID.
	BatchDeleteFederationRelationship(ctx context.Context, in *BatchDeleteFederationRelationshipRequest, opts ...grpc.CallOption) (*BatchDeleteFederationRelationshipResponse, error)
	// Refreshes the bundle from the specified federated trust domain.
	// If there is not a federation relationship configured with the
	// specified trust domain, NOT_FOUND is returned.
	//
	// The caller must be local or present an admin X509-SVID.
	RefreshBundle(ctx context.Context, in *RefreshBundleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type federationManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewFederationManagementClient(cc grpc.ClientConnInterface) FederationManagementClient {
	return &federationManagementClient{cc}
}

func (c *federationManagementClient) ListFederationRelationships(ctx context.Context, in *ListFederationRelationshipsRequest, opts ...grpc.CallOption) (*ListFederationRelationshipsResponse, error) {
	out := new(ListFederationRelationshipsResponse)
	err := c.cc.Invoke(ctx, "/spire.api.server.federationmanagement.v1.FederationManagement/ListFederationRelationships", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationManagementClient) GetFederationRelationship(ctx context.Context, in *GetFederationRelationshipRequest, opts ...grpc.CallOption) (*types.FederationRelationship, error) {
	out := new(types.FederationRelationship)
	err := c.cc.Invoke(ctx, "/spire.api.server.federationmanagement.v1.FederationManagement/GetFederationRelationship", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationManagementClient) BatchCreateFederationRelationship(ctx context.Context, in *BatchCreateFederationRelationshipRequest, opts ...grpc.CallOption) (*BatchCreateFederationRelationshipResponse, error) {
	out := new(BatchCreateFederationRelationshipResponse)
	err := c.cc.Invoke(ctx, "/spire.api.server.federationmanagement.v1.FederationManagement/BatchCreateFederationRelationship", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationManagementClient) BatchUpdateFederationRelationship(ctx context.Context, in *BatchUpdateFederationRelationshipRequest, opts ...grpc.CallOption) (*BatchUpdateFederationRelationshipResponse, error) {
	out := new(BatchUpdateFederationRelationshipResponse)
	err := c.cc.Invoke(ctx, "/spire.api.server.federationmanagement.v1.FederationManagement/BatchUpdateFederationRelationship", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationManagementClient) BatchDeleteFederationRelationship(ctx context.Context, in *BatchDeleteFederationRelationshipRequest, opts ...grpc.CallOption) (*BatchDeleteFederationRelationshipResponse, error) {
	out := new(BatchDeleteFederationRelationshipResponse)
	err := c.cc.Invoke(ctx, "/spire.api.server.federationmanagement.v1.FederationManagement/BatchDeleteFederationRelationship", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationManagementClient) RefreshBundle(ctx context.Context, in *RefreshBundleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/spire.api.server.federationmanagement.v1.FederationManagement/RefreshBundle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FederationManagementServer is the server API for FederationManagement service.
// All implementations must embed UnimplementedFederationManagementServer
// for forward compatibility
type FederationManagementServer interface {
	// Lists federation relationships with other trust domains.
	//
	// The caller must be local or present an admin X509-SVID.
	ListFederationRelationships(context.Context, *ListFederationRelationshipsRequest) (*ListFederationRelationshipsResponse, error)
	// Gets a federation relationship with other trust domain.
	// If there is no federation relationship with the specified
	// trust domain, NOT_FOUND is returned.
	//
	// The caller must be local or present an admin X509-SVID.
	GetFederationRelationship(context.Context, *GetFederationRelationshipRequest) (*types.FederationRelationship, error)
	// Batch creates one or more federation relationships with other trust domains.
	//
	// The caller must be local or present an admin X509-SVID.
	BatchCreateFederationRelationship(context.Context, *BatchCreateFederationRelationshipRequest) (*BatchCreateFederationRelationshipResponse, error)
	// Batch updates one or more federation relationships with other trust domains.
	//
	// The caller must be local or present an admin X509-SVID.
	BatchUpdateFederationRelationship(context.Context, *BatchUpdateFederationRelationshipRequest) (*BatchUpdateFederationRelationshipResponse, error)
	// Batch deletes federation relationships with other trust domains.
	//
	// The caller must be local or present an admin X509-SVID.
	BatchDeleteFederationRelationship(context.Context, *BatchDeleteFederationRelationshipRequest) (*BatchDeleteFederationRelationshipResponse, error)
	// Refreshes the bundle from the specified federated trust domain.
	// If there is not a federation relationship configured with the
	// specified trust domain, NOT_FOUND is returned.
	//
	// The caller must be local or present an admin X509-SVID.
	RefreshBundle(context.Context, *RefreshBundleRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedFederationManagementServer()
}

// UnimplementedFederationManagementServer must be embedded to have forward compatible implementations.
type UnimplementedFederationManagementServer struct {
}

func (UnimplementedFederationManagementServer) ListFederationRelationships(context.Context, *ListFederationRelationshipsRequest) (*ListFederationRelationshipsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFederationRelationships not implemented")
}
func (UnimplementedFederationManagementServer) GetFederationRelationship(context.Context, *GetFederationRelationshipRequest) (*types.FederationRelationship, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFederationRelationship not implemented")
}
func (UnimplementedFederationManagementServer) BatchCreateFederationRelationship(context.Context, *BatchCreateFederationRelationshipRequest) (*BatchCreateFederationRelationshipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchCreateFederationRelationship not implemented")
}
func (UnimplementedFederationManagementServer) BatchUpdateFederationRelationship(context.Context, *BatchUpdateFederationRelationshipRequest) (*BatchUpdateFederationRelationshipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchUpdateFederationRelationship not implemented")
}
func (UnimplementedFederationManagementServer) BatchDeleteFederationRelationship(context.Context, *BatchDeleteFederationRelationshipRequest) (*BatchDeleteFederationRelationshipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDeleteFederationRelationship not implemented")
}
func (UnimplementedFederationManagementServer) RefreshBundle(context.Context, *RefreshBundleRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshBundle not implemented")
}
func (UnimplementedFederationManagementServer) mustEmbedUnimplementedFederationManagementServer() {}

// UnsafeFederationManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FederationManagementServer will
// result in compilation errors.
type UnsafeFederationManagementServer interface {
	mustEmbedUnimplementedFederationManagementServer()
}

func RegisterFederationManagementServer(s grpc.ServiceRegistrar, srv FederationManagementServer) {
	s.RegisterService(&_FederationManagement_serviceDesc, srv)
}

func _FederationManagement_ListFederationRelationships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFederationRelationshipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationManagementServer).ListFederationRelationships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spire.api.server.federationmanagement.v1.FederationManagement/ListFederationRelationships",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationManagementServer).ListFederationRelationships(ctx, req.(*ListFederationRelationshipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationManagement_GetFederationRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFederationRelationshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationManagementServer).GetFederationRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spire.api.server.federationmanagement.v1.FederationManagement/GetFederationRelationship",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationManagementServer).GetFederationRelationship(ctx, req.(*GetFederationRelationshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationManagement_BatchCreateFederationRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCreateFederationRelationshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationManagementServer).BatchCreateFederationRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spire.api.server.federationmanagement.v1.FederationManagement/BatchCreateFederationRelationship",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationManagementServer).BatchCreateFederationRelationship(ctx, req.(*BatchCreateFederationRelationshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationManagement_BatchUpdateFederationRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpdateFederationRelationshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationManagementServer).BatchUpdateFederationRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spire.api.server.federationmanagement.v1.FederationManagement/BatchUpdateFederationRelationship",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationManagementServer).BatchUpdateFederationRelationship(ctx, req.(*BatchUpdateFederationRelationshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationManagement_BatchDeleteFederationRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteFederationRelationshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationManagementServer).BatchDeleteFederationRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spire.api.server.federationmanagement.v1.FederationManagement/BatchDeleteFederationRelationship",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationManagementServer).BatchDeleteFederationRelationship(ctx, req.(*BatchDeleteFederationRelationshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationManagement_RefreshBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationManagementServer).RefreshBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spire.api.server.federationmanagement.v1.FederationManagement/RefreshBundle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationManagementServer).RefreshBundle(ctx, req.(*RefreshBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FederationManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "spire.api.server.federationmanagement.v1.FederationManagement",
	HandlerType: (*FederationManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFederationRelationships",
			Handler:    _FederationManagement_ListFederationRelationships_Handler,
		},
		{
			MethodName: "GetFederationRelationship",
			Handler:    _FederationManagement_GetFederationRelationship_Handler,
		},
		{
			MethodName: "BatchCreateFederationRelationship",
			Handler:    _FederationManagement_BatchCreateFederationRelationship_Handler,
		},
		{
			MethodName: "BatchUpdateFederationRelationship",
			Handler:    _FederationManagement_BatchUpdateFederationRelationship_Handler,
		},
		{
			MethodName: "BatchDeleteFederationRelationship",
			Handler:    _FederationManagement_BatchDeleteFederationRelationship_Handler,
		},
		{
			MethodName: "RefreshBundle",
			Handler:    _FederationManagement_RefreshBundle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spire/api/server/federationmanagement/v1/federationmanagement.proto",
}
