// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: spire/api/agent/logger/v1/logger.proto

package loggerv1

import (
	types "github.com/spiffe/spire-api-sdk/proto/spire/api/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetLogLevelRequest_SetValue int32

const (
	SetLogLevelRequest_PANIC   SetLogLevelRequest_SetValue = 0
	SetLogLevelRequest_FATAL   SetLogLevelRequest_SetValue = 1
	SetLogLevelRequest_ERROR   SetLogLevelRequest_SetValue = 2
	SetLogLevelRequest_WARN    SetLogLevelRequest_SetValue = 3
	SetLogLevelRequest_INFO    SetLogLevelRequest_SetValue = 4
	SetLogLevelRequest_DEBUG   SetLogLevelRequest_SetValue = 5
	SetLogLevelRequest_TRACE   SetLogLevelRequest_SetValue = 6
	SetLogLevelRequest_DEFAULT SetLogLevelRequest_SetValue = 7
)

// Enum value maps for SetLogLevelRequest_SetValue.
var (
	SetLogLevelRequest_SetValue_name = map[int32]string{
		0: "PANIC",
		1: "FATAL",
		2: "ERROR",
		3: "WARN",
		4: "INFO",
		5: "DEBUG",
		6: "TRACE",
		7: "DEFAULT",
	}
	SetLogLevelRequest_SetValue_value = map[string]int32{
		"PANIC":   0,
		"FATAL":   1,
		"ERROR":   2,
		"WARN":    3,
		"INFO":    4,
		"DEBUG":   5,
		"TRACE":   6,
		"DEFAULT": 7,
	}
)

func (x SetLogLevelRequest_SetValue) Enum() *SetLogLevelRequest_SetValue {
	p := new(SetLogLevelRequest_SetValue)
	*p = x
	return p
}

func (x SetLogLevelRequest_SetValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetLogLevelRequest_SetValue) Descriptor() protoreflect.EnumDescriptor {
	return file_spire_api_agent_logger_v1_logger_proto_enumTypes[0].Descriptor()
}

func (SetLogLevelRequest_SetValue) Type() protoreflect.EnumType {
	return &file_spire_api_agent_logger_v1_logger_proto_enumTypes[0]
}

func (x SetLogLevelRequest_SetValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetLogLevelRequest_SetValue.Descriptor instead.
func (SetLogLevelRequest_SetValue) EnumDescriptor() ([]byte, []int) {
	return file_spire_api_agent_logger_v1_logger_proto_rawDescGZIP(), []int{1, 0}
}

type GetLoggerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLoggerRequest) Reset() {
	*x = GetLoggerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spire_api_agent_logger_v1_logger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLoggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoggerRequest) ProtoMessage() {}

func (x *GetLoggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_agent_logger_v1_logger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoggerRequest.ProtoReflect.Descriptor instead.
func (*GetLoggerRequest) Descriptor() ([]byte, []int) {
	return file_spire_api_agent_logger_v1_logger_proto_rawDescGZIP(), []int{0}
}

type SetLogLevelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The new level the logger should assume
	SetLevel SetLogLevelRequest_SetValue `protobuf:"varint,1,opt,name=set_level,json=setLevel,proto3,enum=spire.api.agent.logger.v1.SetLogLevelRequest_SetValue" json:"set_level,omitempty"`
}

func (x *SetLogLevelRequest) Reset() {
	*x = SetLogLevelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spire_api_agent_logger_v1_logger_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLogLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLogLevelRequest) ProtoMessage() {}

func (x *SetLogLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_agent_logger_v1_logger_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLogLevelRequest.ProtoReflect.Descriptor instead.
func (*SetLogLevelRequest) Descriptor() ([]byte, []int) {
	return file_spire_api_agent_logger_v1_logger_proto_rawDescGZIP(), []int{1}
}

func (x *SetLogLevelRequest) GetSetLevel() SetLogLevelRequest_SetValue {
	if x != nil {
		return x.SetLevel
	}
	return SetLogLevelRequest_PANIC
}

var File_spire_api_agent_logger_v1_logger_proto protoreflect.FileDescriptor

var file_spire_api_agent_logger_v1_logger_proto_rawDesc = []byte{
	0x0a, 0x26, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2f, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x67, 0x67,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2f, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xcd, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x67,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x53, 0x0a, 0x09,
	0x73, 0x65, 0x74, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x36, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x4c,
	0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53,
	0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x08, 0x73, 0x65, 0x74, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x22, 0x62, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x09, 0x0a,
	0x05, 0x50, 0x41, 0x4e, 0x49, 0x43, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x41, 0x54, 0x41,
	0x4c, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x08,
	0x0a, 0x04, 0x57, 0x41, 0x52, 0x4e, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x46, 0x4f,
	0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x45, 0x42, 0x55, 0x47, 0x10, 0x05, 0x12, 0x09, 0x0a,
	0x05, 0x54, 0x52, 0x41, 0x43, 0x45, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x46, 0x41,
	0x55, 0x4c, 0x54, 0x10, 0x07, 0x32, 0xb2, 0x01, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x72,
	0x12, 0x51, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x12, 0x2b, 0x2e,
	0x73, 0x70, 0x69, 0x72, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e,
	0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67,
	0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x70, 0x69,
	0x72, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4c, 0x6f, 0x67,
	0x67, 0x65, 0x72, 0x12, 0x55, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x2d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x74, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x42, 0x4a, 0x5a, 0x48, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x70, 0x69, 0x66, 0x66, 0x65, 0x2f,
	0x73, 0x70, 0x69, 0x72, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2f, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x6c, 0x6f,
	0x67, 0x67, 0x65, 0x72, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spire_api_agent_logger_v1_logger_proto_rawDescOnce sync.Once
	file_spire_api_agent_logger_v1_logger_proto_rawDescData = file_spire_api_agent_logger_v1_logger_proto_rawDesc
)

func file_spire_api_agent_logger_v1_logger_proto_rawDescGZIP() []byte {
	file_spire_api_agent_logger_v1_logger_proto_rawDescOnce.Do(func() {
		file_spire_api_agent_logger_v1_logger_proto_rawDescData = protoimpl.X.CompressGZIP(file_spire_api_agent_logger_v1_logger_proto_rawDescData)
	})
	return file_spire_api_agent_logger_v1_logger_proto_rawDescData
}

var file_spire_api_agent_logger_v1_logger_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spire_api_agent_logger_v1_logger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_spire_api_agent_logger_v1_logger_proto_goTypes = []interface{}{
	(SetLogLevelRequest_SetValue)(0), // 0: spire.api.agent.logger.v1.SetLogLevelRequest.SetValue
	(*GetLoggerRequest)(nil),         // 1: spire.api.agent.logger.v1.GetLoggerRequest
	(*SetLogLevelRequest)(nil),       // 2: spire.api.agent.logger.v1.SetLogLevelRequest
	(*types.Logger)(nil),             // 3: spire.api.types.Logger
}
var file_spire_api_agent_logger_v1_logger_proto_depIdxs = []int32{
	0, // 0: spire.api.agent.logger.v1.SetLogLevelRequest.set_level:type_name -> spire.api.agent.logger.v1.SetLogLevelRequest.SetValue
	1, // 1: spire.api.agent.logger.v1.Logger.GetLogger:input_type -> spire.api.agent.logger.v1.GetLoggerRequest
	2, // 2: spire.api.agent.logger.v1.Logger.SetLogLevel:input_type -> spire.api.agent.logger.v1.SetLogLevelRequest
	3, // 3: spire.api.agent.logger.v1.Logger.GetLogger:output_type -> spire.api.types.Logger
	3, // 4: spire.api.agent.logger.v1.Logger.SetLogLevel:output_type -> spire.api.types.Logger
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spire_api_agent_logger_v1_logger_proto_init() }
func file_spire_api_agent_logger_v1_logger_proto_init() {
	if File_spire_api_agent_logger_v1_logger_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spire_api_agent_logger_v1_logger_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLoggerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spire_api_agent_logger_v1_logger_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLogLevelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spire_api_agent_logger_v1_logger_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spire_api_agent_logger_v1_logger_proto_goTypes,
		DependencyIndexes: file_spire_api_agent_logger_v1_logger_proto_depIdxs,
		EnumInfos:         file_spire_api_agent_logger_v1_logger_proto_enumTypes,
		MessageInfos:      file_spire_api_agent_logger_v1_logger_proto_msgTypes,
	}.Build()
	File_spire_api_agent_logger_v1_logger_proto = out.File
	file_spire_api_agent_logger_v1_logger_proto_rawDesc = nil
	file_spire_api_agent_logger_v1_logger_proto_goTypes = nil
	file_spire_api_agent_logger_v1_logger_proto_depIdxs = nil
}
