// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: spire/api/types/federationrelationship.proto

package types

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FederationRelationship struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The trust domain name (e.g., "example.org") to federate with.
	TrustDomain string `protobuf:"bytes,1,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	// URL of the SPIFFE bundle endpoint that provides the trust
	// bundle to federate with. Must use the HTTPS protocol.
	BundleEndpointUrl string `protobuf:"bytes,2,opt,name=bundle_endpoint_url,json=bundleEndpointUrl,proto3" json:"bundle_endpoint_url,omitempty"`
	// Required. The endpoint profile type.
	//
	// Types that are assignable to BundleEndpointProfile:
	//	*FederationRelationship_HttpsWeb
	//	*FederationRelationship_HttpsSpiffe
	BundleEndpointProfile isFederationRelationship_BundleEndpointProfile `protobuf_oneof:"bundle_endpoint_profile"`
}

func (x *FederationRelationship) Reset() {
	*x = FederationRelationship{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spire_api_types_federationrelationship_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FederationRelationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederationRelationship) ProtoMessage() {}

func (x *FederationRelationship) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_types_federationrelationship_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederationRelationship.ProtoReflect.Descriptor instead.
func (*FederationRelationship) Descriptor() ([]byte, []int) {
	return file_spire_api_types_federationrelationship_proto_rawDescGZIP(), []int{0}
}

func (x *FederationRelationship) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

func (x *FederationRelationship) GetBundleEndpointUrl() string {
	if x != nil {
		return x.BundleEndpointUrl
	}
	return ""
}

func (m *FederationRelationship) GetBundleEndpointProfile() isFederationRelationship_BundleEndpointProfile {
	if m != nil {
		return m.BundleEndpointProfile
	}
	return nil
}

func (x *FederationRelationship) GetHttpsWeb() *WebPKI {
	if x, ok := x.GetBundleEndpointProfile().(*FederationRelationship_HttpsWeb); ok {
		return x.HttpsWeb
	}
	return nil
}

func (x *FederationRelationship) GetHttpsSpiffe() *SPIFFEAuthentication {
	if x, ok := x.GetBundleEndpointProfile().(*FederationRelationship_HttpsSpiffe); ok {
		return x.HttpsSpiffe
	}
	return nil
}

type isFederationRelationship_BundleEndpointProfile interface {
	isFederationRelationship_BundleEndpointProfile()
}

type FederationRelationship_HttpsWeb struct {
	// Use Web PKI endpoint profile.
	HttpsWeb *WebPKI `protobuf:"bytes,3,opt,name=https_web,json=httpsWeb,proto3,oneof"`
}

type FederationRelationship_HttpsSpiffe struct {
	// Use SPIFFE Authentication endpoint profile.
	HttpsSpiffe *SPIFFEAuthentication `protobuf:"bytes,4,opt,name=https_spiffe,json=httpsSpiffe,proto3,oneof"`
}

func (*FederationRelationship_HttpsWeb) isFederationRelationship_BundleEndpointProfile() {}

func (*FederationRelationship_HttpsSpiffe) isFederationRelationship_BundleEndpointProfile() {}

type SPIFFEAuthentication struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Specifies the expected SPIFFE ID of the SPIFFE bundle endpoint server.
	// The SPIRE Server SPIFFE ID within the trust domain will be
	// used if this is empty.
	EndpointSpiffeId string `protobuf:"bytes,1,opt,name=endpoint_spiffe_id,json=endpointSpiffeId,proto3" json:"endpoint_spiffe_id,omitempty"`
}

func (x *SPIFFEAuthentication) Reset() {
	*x = SPIFFEAuthentication{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spire_api_types_federationrelationship_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SPIFFEAuthentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPIFFEAuthentication) ProtoMessage() {}

func (x *SPIFFEAuthentication) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_types_federationrelationship_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPIFFEAuthentication.ProtoReflect.Descriptor instead.
func (*SPIFFEAuthentication) Descriptor() ([]byte, []int) {
	return file_spire_api_types_federationrelationship_proto_rawDescGZIP(), []int{1}
}

func (x *SPIFFEAuthentication) GetEndpointSpiffeId() string {
	if x != nil {
		return x.EndpointSpiffeId
	}
	return ""
}

type WebPKI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WebPKI) Reset() {
	*x = WebPKI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spire_api_types_federationrelationship_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebPKI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebPKI) ProtoMessage() {}

func (x *WebPKI) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_types_federationrelationship_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebPKI.ProtoReflect.Descriptor instead.
func (*WebPKI) Descriptor() ([]byte, []int) {
	return file_spire_api_types_federationrelationship_proto_rawDescGZIP(), []int{2}
}

type FederationRelationshipMask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// bundle_endpoint_url field mask.
	BundleEndpointUrl bool `protobuf:"varint,1,opt,name=bundle_endpoint_url,json=bundleEndpointUrl,proto3" json:"bundle_endpoint_url,omitempty"`
	// bundle_endpoint_profile field mask.
	BundleEndpointProfile bool `protobuf:"varint,2,opt,name=bundle_endpoint_profile,json=bundleEndpointProfile,proto3" json:"bundle_endpoint_profile,omitempty"`
}

func (x *FederationRelationshipMask) Reset() {
	*x = FederationRelationshipMask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spire_api_types_federationrelationship_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FederationRelationshipMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederationRelationshipMask) ProtoMessage() {}

func (x *FederationRelationshipMask) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_types_federationrelationship_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederationRelationshipMask.ProtoReflect.Descriptor instead.
func (*FederationRelationshipMask) Descriptor() ([]byte, []int) {
	return file_spire_api_types_federationrelationship_proto_rawDescGZIP(), []int{3}
}

func (x *FederationRelationshipMask) GetBundleEndpointUrl() bool {
	if x != nil {
		return x.BundleEndpointUrl
	}
	return false
}

func (x *FederationRelationshipMask) GetBundleEndpointProfile() bool {
	if x != nil {
		return x.BundleEndpointProfile
	}
	return false
}

var File_spire_api_types_federationrelationship_proto protoreflect.FileDescriptor

var file_spire_api_types_federationrelationship_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2f, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x72, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x73, 0x70, 0x69, 0x72, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22,
	0x8a, 0x02, 0x0a, 0x16, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x72,
	0x75, 0x73, 0x74, 0x5f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x74, 0x72, 0x75, 0x73, 0x74, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x2e, 0x0a,
	0x13, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x62, 0x75, 0x6e, 0x64,
	0x6c, 0x65, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x36, 0x0a,
	0x09, 0x68, 0x74, 0x74, 0x70, 0x73, 0x5f, 0x77, 0x65, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x57, 0x65, 0x62, 0x50, 0x4b, 0x49, 0x48, 0x00, 0x52, 0x08, 0x68, 0x74, 0x74,
	0x70, 0x73, 0x57, 0x65, 0x62, 0x12, 0x4a, 0x0a, 0x0c, 0x68, 0x74, 0x74, 0x70, 0x73, 0x5f, 0x73,
	0x70, 0x69, 0x66, 0x66, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x70,
	0x69, 0x72, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x50,
	0x49, 0x46, 0x46, 0x45, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0b, 0x68, 0x74, 0x74, 0x70, 0x73, 0x53, 0x70, 0x69, 0x66, 0x66,
	0x65, 0x42, 0x19, 0x0a, 0x17, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x65, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x44, 0x0a, 0x14,
	0x53, 0x50, 0x49, 0x46, 0x46, 0x45, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x12, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x5f, 0x73, 0x70, 0x69, 0x66, 0x66, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x53, 0x70, 0x69, 0x66, 0x66, 0x65,
	0x49, 0x64, 0x22, 0x08, 0x0a, 0x06, 0x57, 0x65, 0x62, 0x50, 0x4b, 0x49, 0x22, 0x84, 0x01, 0x0a,
	0x1a, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x2e, 0x0a, 0x13, 0x62,
	0x75, 0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65,
	0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x36, 0x0a, 0x17, 0x62,
	0x75, 0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x15, 0x62, 0x75,
	0x6e, 0x64, 0x6c, 0x65, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x73, 0x70, 0x69, 0x66, 0x66, 0x65, 0x2f, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2d, 0x61,
	0x70, 0x69, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x69,
	0x72, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spire_api_types_federationrelationship_proto_rawDescOnce sync.Once
	file_spire_api_types_federationrelationship_proto_rawDescData = file_spire_api_types_federationrelationship_proto_rawDesc
)

func file_spire_api_types_federationrelationship_proto_rawDescGZIP() []byte {
	file_spire_api_types_federationrelationship_proto_rawDescOnce.Do(func() {
		file_spire_api_types_federationrelationship_proto_rawDescData = protoimpl.X.CompressGZIP(file_spire_api_types_federationrelationship_proto_rawDescData)
	})
	return file_spire_api_types_federationrelationship_proto_rawDescData
}

var file_spire_api_types_federationrelationship_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_spire_api_types_federationrelationship_proto_goTypes = []interface{}{
	(*FederationRelationship)(nil),     // 0: spire.api.types.FederationRelationship
	(*SPIFFEAuthentication)(nil),       // 1: spire.api.types.SPIFFEAuthentication
	(*WebPKI)(nil),                     // 2: spire.api.types.WebPKI
	(*FederationRelationshipMask)(nil), // 3: spire.api.types.FederationRelationshipMask
}
var file_spire_api_types_federationrelationship_proto_depIdxs = []int32{
	2, // 0: spire.api.types.FederationRelationship.https_web:type_name -> spire.api.types.WebPKI
	1, // 1: spire.api.types.FederationRelationship.https_spiffe:type_name -> spire.api.types.SPIFFEAuthentication
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_spire_api_types_federationrelationship_proto_init() }
func file_spire_api_types_federationrelationship_proto_init() {
	if File_spire_api_types_federationrelationship_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spire_api_types_federationrelationship_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FederationRelationship); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spire_api_types_federationrelationship_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SPIFFEAuthentication); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spire_api_types_federationrelationship_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebPKI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spire_api_types_federationrelationship_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FederationRelationshipMask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_spire_api_types_federationrelationship_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*FederationRelationship_HttpsWeb)(nil),
		(*FederationRelationship_HttpsSpiffe)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spire_api_types_federationrelationship_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spire_api_types_federationrelationship_proto_goTypes,
		DependencyIndexes: file_spire_api_types_federationrelationship_proto_depIdxs,
		MessageInfos:      file_spire_api_types_federationrelationship_proto_msgTypes,
	}.Build()
	File_spire_api_types_federationrelationship_proto = out.File
	file_spire_api_types_federationrelationship_proto_rawDesc = nil
	file_spire_api_types_federationrelationship_proto_goTypes = nil
	file_spire_api_types_federationrelationship_proto_depIdxs = nil
}
