// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: spire/api/types/selectorreference.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SelectorReference conveys a workload identified by a set of selectors
// supplied by the caller, rather than one the SPIRE Agent resolves and attests
// for itself.
//
// It is intended for use as a SPIFFE Broker API WorkloadReference extension
// type, by brokers that perform their own workload attestation using mechanisms
// SPIRE has no attestor for, and that map the result onto SPIRE's selector
// vocabulary.
//
// Unlike reference types the agent resolves itself, a SelectorReference cannot
// be independently verified: there is no object to resolve and no process to
// inspect, so the selectors are treated as already attested. A caller able to
// use this reference type can therefore obtain SVIDs for any identity whose
// selectors it can name. Implementations MUST NOT accept this reference type
// from a caller that has not been explicitly authorized to assert selectors,
// and MUST NOT treat a general grant of "any reference type" as such an
// authorization.
type SelectorReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The selectors describing the workload. Must not be empty.
	Selectors     []*Selector `protobuf:"bytes,1,rep,name=selectors,proto3" json:"selectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectorReference) Reset() {
	*x = SelectorReference{}
	mi := &file_spire_api_types_selectorreference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectorReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectorReference) ProtoMessage() {}

func (x *SelectorReference) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_types_selectorreference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectorReference.ProtoReflect.Descriptor instead.
func (*SelectorReference) Descriptor() ([]byte, []int) {
	return file_spire_api_types_selectorreference_proto_rawDescGZIP(), []int{0}
}

func (x *SelectorReference) GetSelectors() []*Selector {
	if x != nil {
		return x.Selectors
	}
	return nil
}

var File_spire_api_types_selectorreference_proto protoreflect.FileDescriptor

const file_spire_api_types_selectorreference_proto_rawDesc = "" +
	"\n" +
	"'spire/api/types/selectorreference.proto\x12\x0fspire.api.types\x1a\x1espire/api/types/selector.proto\"L\n" +
	"\x11SelectorReference\x127\n" +
	"\tselectors\x18\x01 \x03(\v2\x19.spire.api.types.SelectorR\tselectorsB7Z5github.com/spiffe/spire-api-sdk/proto/spire/api/typesb\x06proto3"

var (
	file_spire_api_types_selectorreference_proto_rawDescOnce sync.Once
	file_spire_api_types_selectorreference_proto_rawDescData []byte
)

func file_spire_api_types_selectorreference_proto_rawDescGZIP() []byte {
	file_spire_api_types_selectorreference_proto_rawDescOnce.Do(func() {
		file_spire_api_types_selectorreference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spire_api_types_selectorreference_proto_rawDesc), len(file_spire_api_types_selectorreference_proto_rawDesc)))
	})
	return file_spire_api_types_selectorreference_proto_rawDescData
}

var file_spire_api_types_selectorreference_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_spire_api_types_selectorreference_proto_goTypes = []any{
	(*SelectorReference)(nil), // 0: spire.api.types.SelectorReference
	(*Selector)(nil),          // 1: spire.api.types.Selector
}
var file_spire_api_types_selectorreference_proto_depIdxs = []int32{
	1, // 0: spire.api.types.SelectorReference.selectors:type_name -> spire.api.types.Selector
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spire_api_types_selectorreference_proto_init() }
func file_spire_api_types_selectorreference_proto_init() {
	if File_spire_api_types_selectorreference_proto != nil {
		return
	}
	file_spire_api_types_selector_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spire_api_types_selectorreference_proto_rawDesc), len(file_spire_api_types_selectorreference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spire_api_types_selectorreference_proto_goTypes,
		DependencyIndexes: file_spire_api_types_selectorreference_proto_depIdxs,
		MessageInfos:      file_spire_api_types_selectorreference_proto_msgTypes,
	}.Build()
	File_spire_api_types_selectorreference_proto = out.File
	file_spire_api_types_selectorreference_proto_goTypes = nil
	file_spire_api_types_selectorreference_proto_depIdxs = nil
}
