// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: spiffe/reference/reference.proto

package reference

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The WorkloadPIDReference message conveys a process id reference of a workload
// running in the same environment.
type WorkloadPIDReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The process id of the workload. MUST be a positive integer.
	Pid           int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadPIDReference) Reset() {
	*x = WorkloadPIDReference{}
	mi := &file_spiffe_reference_reference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadPIDReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadPIDReference) ProtoMessage() {}

func (x *WorkloadPIDReference) ProtoReflect() protoreflect.Message {
	mi := &file_spiffe_reference_reference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadPIDReference.ProtoReflect.Descriptor instead.
func (*WorkloadPIDReference) Descriptor() ([]byte, []int) {
	return file_spiffe_reference_reference_proto_rawDescGZIP(), []int{0}
}

func (x *WorkloadPIDReference) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// The KubernetesPodUIDReference message conveys a Kubernetes pod UID reference of a
// workload running in a Kubernetes cluster.
type KubernetesPodUIDReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The UID of the Kubernetes pod. MUST be a valid UUID string.
	Uid           string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesPodUIDReference) Reset() {
	*x = KubernetesPodUIDReference{}
	mi := &file_spiffe_reference_reference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesPodUIDReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesPodUIDReference) ProtoMessage() {}

func (x *KubernetesPodUIDReference) ProtoReflect() protoreflect.Message {
	mi := &file_spiffe_reference_reference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesPodUIDReference.ProtoReflect.Descriptor instead.
func (*KubernetesPodUIDReference) Descriptor() ([]byte, []int) {
	return file_spiffe_reference_reference_proto_rawDescGZIP(), []int{1}
}

func (x *KubernetesPodUIDReference) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

var File_spiffe_reference_reference_proto protoreflect.FileDescriptor

const file_spiffe_reference_reference_proto_rawDesc = "" +
	"\n" +
	" spiffe/reference/reference.proto\x12\x10spiffe.reference\"(\n" +
	"\x14WorkloadPIDReference\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\"-\n" +
	"\x19KubernetesPodUIDReference\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uidBBZ@github.com/spiffe/spire-api-sdk/proto/spiffe/reference;referenceb\x06proto3"

var (
	file_spiffe_reference_reference_proto_rawDescOnce sync.Once
	file_spiffe_reference_reference_proto_rawDescData []byte
)

func file_spiffe_reference_reference_proto_rawDescGZIP() []byte {
	file_spiffe_reference_reference_proto_rawDescOnce.Do(func() {
		file_spiffe_reference_reference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spiffe_reference_reference_proto_rawDesc), len(file_spiffe_reference_reference_proto_rawDesc)))
	})
	return file_spiffe_reference_reference_proto_rawDescData
}

var file_spiffe_reference_reference_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_spiffe_reference_reference_proto_goTypes = []any{
	(*WorkloadPIDReference)(nil),      // 0: spiffe.reference.WorkloadPIDReference
	(*KubernetesPodUIDReference)(nil), // 1: spiffe.reference.KubernetesPodUIDReference
}
var file_spiffe_reference_reference_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spiffe_reference_reference_proto_init() }
func file_spiffe_reference_reference_proto_init() {
	if File_spiffe_reference_reference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spiffe_reference_reference_proto_rawDesc), len(file_spiffe_reference_reference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spiffe_reference_reference_proto_goTypes,
		DependencyIndexes: file_spiffe_reference_reference_proto_depIdxs,
		MessageInfos:      file_spiffe_reference_reference_proto_msgTypes,
	}.Build()
	File_spiffe_reference_reference_proto = out.File
	file_spiffe_reference_reference_proto_goTypes = nil
	file_spiffe_reference_reference_proto_depIdxs = nil
}
