// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: spire/api/server/debug/v1/debug.proto

package debugv1

import (
	types "github.com/spiffe/spire-api-sdk/proto/spire/api/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_spire_api_server_debug_v1_debug_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_server_debug_v1_debug_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_spire_api_server_debug_v1_debug_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server SVID chain
	SvidChain []*GetInfoResponse_Cert `protobuf:"bytes,1,rep,name=svid_chain,json=svidChain,proto3" json:"svid_chain,omitempty"`
	// Server uptime in seconds
	Uptime int32 `protobuf:"varint,2,opt,name=uptime,proto3" json:"uptime,omitempty"`
	// Amount of registered agents
	AgentsCount int32 `protobuf:"varint,3,opt,name=agents_count,json=agentsCount,proto3" json:"agents_count,omitempty"`
	// Amount of federated bundles
	FederatedBundlesCount int32 `protobuf:"varint,4,opt,name=federated_bundles_count,json=federatedBundlesCount,proto3" json:"federated_bundles_count,omitempty"`
	// Amount of registration entries on database
	EntriesCount  int32 `protobuf:"varint,5,opt,name=entries_count,json=entriesCount,proto3" json:"entries_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_spire_api_server_debug_v1_debug_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_server_debug_v1_debug_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_spire_api_server_debug_v1_debug_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetSvidChain() []*GetInfoResponse_Cert {
	if x != nil {
		return x.SvidChain
	}
	return nil
}

func (x *GetInfoResponse) GetUptime() int32 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *GetInfoResponse) GetAgentsCount() int32 {
	if x != nil {
		return x.AgentsCount
	}
	return 0
}

func (x *GetInfoResponse) GetFederatedBundlesCount() int32 {
	if x != nil {
		return x.FederatedBundlesCount
	}
	return 0
}

func (x *GetInfoResponse) GetEntriesCount() int32 {
	if x != nil {
		return x.EntriesCount
	}
	return 0
}

type GetInfoResponse_Cert struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Certificate SPIFFE ID
	Id *types.SPIFFEID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Expiration time
	ExpiresAt int64 `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Subject
	Subject       string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse_Cert) Reset() {
	*x = GetInfoResponse_Cert{}
	mi := &file_spire_api_server_debug_v1_debug_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse_Cert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse_Cert) ProtoMessage() {}

func (x *GetInfoResponse_Cert) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_server_debug_v1_debug_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse_Cert.ProtoReflect.Descriptor instead.
func (*GetInfoResponse_Cert) Descriptor() ([]byte, []int) {
	return file_spire_api_server_debug_v1_debug_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetInfoResponse_Cert) GetId() *types.SPIFFEID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GetInfoResponse_Cert) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *GetInfoResponse_Cert) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

var File_spire_api_server_debug_v1_debug_proto protoreflect.FileDescriptor

const file_spire_api_server_debug_v1_debug_proto_rawDesc = "" +
	"\n" +
	"%spire/api/server/debug/v1/debug.proto\x12\x19spire.api.server.debug.v1\x1a\x1espire/api/types/spiffeid.proto\"\x10\n" +
	"\x0eGetInfoRequest\"\xe5\x02\n" +
	"\x0fGetInfoResponse\x12N\n" +
	"\n" +
	"svid_chain\x18\x01 \x03(\v2/.spire.api.server.debug.v1.GetInfoResponse.CertR\tsvidChain\x12\x16\n" +
	"\x06uptime\x18\x02 \x01(\x05R\x06uptime\x12!\n" +
	"\fagents_count\x18\x03 \x01(\x05R\vagentsCount\x126\n" +
	"\x17federated_bundles_count\x18\x04 \x01(\x05R\x15federatedBundlesCount\x12#\n" +
	"\rentries_count\x18\x05 \x01(\x05R\fentriesCount\x1aj\n" +
	"\x04Cert\x12)\n" +
	"\x02id\x18\x01 \x01(\v2\x19.spire.api.types.SPIFFEIDR\x02id\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject2i\n" +
	"\x05Debug\x12`\n" +
	"\aGetInfo\x12).spire.api.server.debug.v1.GetInfoRequest\x1a*.spire.api.server.debug.v1.GetInfoResponseBIZGgithub.com/spiffe/spire-api-sdk/proto/spire/api/server/debug/v1;debugv1b\x06proto3"

var (
	file_spire_api_server_debug_v1_debug_proto_rawDescOnce sync.Once
	file_spire_api_server_debug_v1_debug_proto_rawDescData []byte
)

func file_spire_api_server_debug_v1_debug_proto_rawDescGZIP() []byte {
	file_spire_api_server_debug_v1_debug_proto_rawDescOnce.Do(func() {
		file_spire_api_server_debug_v1_debug_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spire_api_server_debug_v1_debug_proto_rawDesc), len(file_spire_api_server_debug_v1_debug_proto_rawDesc)))
	})
	return file_spire_api_server_debug_v1_debug_proto_rawDescData
}

var file_spire_api_server_debug_v1_debug_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spire_api_server_debug_v1_debug_proto_goTypes = []any{
	(*GetInfoRequest)(nil),       // 0: spire.api.server.debug.v1.GetInfoRequest
	(*GetInfoResponse)(nil),      // 1: spire.api.server.debug.v1.GetInfoResponse
	(*GetInfoResponse_Cert)(nil), // 2: spire.api.server.debug.v1.GetInfoResponse.Cert
	(*types.SPIFFEID)(nil),       // 3: spire.api.types.SPIFFEID
}
var file_spire_api_server_debug_v1_debug_proto_depIdxs = []int32{
	2, // 0: spire.api.server.debug.v1.GetInfoResponse.svid_chain:type_name -> spire.api.server.debug.v1.GetInfoResponse.Cert
	3, // 1: spire.api.server.debug.v1.GetInfoResponse.Cert.id:type_name -> spire.api.types.SPIFFEID
	0, // 2: spire.api.server.debug.v1.Debug.GetInfo:input_type -> spire.api.server.debug.v1.GetInfoRequest
	1, // 3: spire.api.server.debug.v1.Debug.GetInfo:output_type -> spire.api.server.debug.v1.GetInfoResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_spire_api_server_debug_v1_debug_proto_init() }
func file_spire_api_server_debug_v1_debug_proto_init() {
	if File_spire_api_server_debug_v1_debug_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spire_api_server_debug_v1_debug_proto_rawDesc), len(file_spire_api_server_debug_v1_debug_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spire_api_server_debug_v1_debug_proto_goTypes,
		DependencyIndexes: file_spire_api_server_debug_v1_debug_proto_depIdxs,
		MessageInfos:      file_spire_api_server_debug_v1_debug_proto_msgTypes,
	}.Build()
	File_spire_api_server_debug_v1_debug_proto = out.File
	file_spire_api_server_debug_v1_debug_proto_goTypes = nil
	file_spire_api_server_debug_v1_debug_proto_depIdxs = nil
}
