name: PR Build
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  generate-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache: true
          cache-dependency-path: go.sum
          go-version-file: go.mod
      - run: make generate-check
